const mounjaroData = [
  {
    id: 1,
    pharmacyName: "Care Pharmacy",
    websiteURL: "https://www.carepharmacy.com/",
    dosage: "2.5 mg",
    rating: "3.8",
    price: "147.89",
    quantity: "20",
    date: "07-05-2024",
    discountedPrice: "0",
    discount: "SAVE22 | SAVE22NY *22% Off 1st order (Expires 30/4)",
  },
  {
    id: 2,
    pharmacyName: "HealthPlus Pharmacy",
    websiteURL: "https://www.healthpluspharmacy.com/",
    dosage: "5 mg",
    rating: "4.4",
    price: "128.59",
    quantity: "1",
    date: "15-01-2024",
    discountedPrice: "50",
    discount: "FIRST £25 Off 1st order 2.5mg only",
  },
  {
    id: 3,
    pharmacyName: "Wellness Pharmacy",
    websiteURL: "https://www.wellnesspharmacy.com/",
    dosage: "7.5 mg",
    rating: "4.9",
    price: "129.74",
    quantity: "7",
    date: "19-11-2024",
    discountedPrice: "25",
    discount: "",
  },
  {
    id: 4,
    pharmacyName: "MediCare Pharmacy",
    websiteURL: "https://www.medicarepharmacy.com/",
    dosage: "10 mg",
    rating: "4.9",
    price: "104.39",
    quantity: "16",
    date: "14-03-2024",
    discountedPrice: "",
    discount: "CLOUDDOSE £5 Off",
  },
  {
    id: 5,
    pharmacyName: "LifeLine Pharmacy",
    websiteURL: "https://www.lifelinepharmacy.com/",
    dosage: "12.5 mg",
    rating: "4.2",
    price: "114.92",
    quantity: "6",
    date: "03-08-2024",
    discountedPrice: "",
    discount: "",
  },
  {
    id: 6,
    pharmacyName: "CityMed Pharmacy",
    websiteURL: "https://www.citymedpharmacy.com/",
    dosage: "15 mg",
    rating: "4.4",
    price: "147.74",
    quantity: "11",
    date: "15-01-2024",
    discountedPrice: "",
    discount: "	APRIL15 | MYHEALTH15 | RETURN15 15% Off",
  },
  {
    id: 7,
    pharmacyName: "PharmaCare",
    websiteURL: "https://www.pharmacare.com/",
    dosage: "2.5 mg",
    rating: "4.9",
    price: "116.60",
    quantity: "16",
    date: "15-04-2024",
    discountedPrice: "50",
    discount: "	**35% Off Auto Applied 2.5mg, *25% Off Auto Applied All other doses 1st 1000 customers ",
  },
  {
    id: 8,
    pharmacyName: "HealthFirst Pharmacy",
    websiteURL: "https://www.healthfirstpharmacy.com/",
    dosage: "5 mg",
    rating: "3.8",
    price: "136.99",
    quantity: "11",
    date: "04-05-2024",
    discountedPrice: "50",
    discount: "	LOSE15 15% Off new customers Refer a friend - £15 Discount (New order info required) Price Match Available Discounts on multi",
  },
  {
    id: 9,
    pharmacyName: "Trust Pharmacy",
    websiteURL: "https://www.trustpharmacy.com/",
    dosage: "7.5 mg",
    rating: "4.9",
    price: "115.10",
    quantity: "20",
    date: "10-08-2024",
    discountedPrice: "50",
    discount: " 25% Off for the 1st 4 months",
  },
  {
    id: 10,
    pharmacyName: "GoodHealth Pharmacy",
    websiteURL: "https://www.goodhealthpharmacy.com/",
    dosage: "10 mg",
    rating: "4.8",
    price: "100.05",
    quantity: "8",
    date: "29-03-2024",
    discountedPrice: "50",
    discount: "",
  },
  {
    id: 11,
    pharmacyName: "SafeMed Pharmacy",
    websiteURL: "https://www.safemedpharmacy.com/",
    dosage: "12.5 mg",
    rating: "4.2",
    price: "145.99",
    quantity: "14",
    date: "20-02-2024",
    discountedPrice: "50",
    discount: "45% Off 1st order. Full price charged each month for subscription",
  },
  {
    id: 12,
    pharmacyName: "Prime Pharmacy",
    websiteURL: "https://www.primepharmacy.com/",
    dosage: "15 mg",
    rating: "4.7",
    price: "139.99",
    quantity: "13",
    date: "22-06-2024",
    discountedPrice: "50",
    discount: "	SAVE2025 *£30 Off 1st order NEWME £20 Off all orders Bluelight discount £15 Maintenance Packages Available",
  },
  {
    id: 13,
    pharmacyName: "WellCare Pharmacy",
    websiteURL: "https://www.wellcarepharmacy.com/",
    dosage: "2.5 mg",
    rating: "4.1",
    price: "132.50",
    quantity: "9",
    date: "11-07-2024",
    discountedPrice: "50",
    discount: "	PCVZNWW6 £50 Off 1st order AZNPD2E3 £20 Off Repeat",
  },
  {
    id: 14,
    pharmacyName: "MediHealth Pharmacy",
    websiteURL: "https://www.medihealthpharmacy.com/",
    dosage: "5 mg",
    rating: "3.9",
    price: "148.00",
    quantity: "17",
    date: "18-09-2024",
    discountedPrice: "50",
    discount: "	WLNEW30 30% Off new customers",
  },
  // …and 40 more entries in the same pattern
];

export default mounjaroData;
