import { MdLocalPharmacy } from "react-icons/md";

const mounjaroData = [
    {
      pharmacyName: "Care Pharmacy",
      websiteURL: "https://www.carepharmacy.com/",
      dosage: "2.5 mg/0.5 mL",
      rating: "3.8",
      price: "147.89",
      quantity: "20",
      date: "07-05-2024",
    },
    {
      pharmacyName: "HealthPlus Pharmacy",
      websiteURL: "https://www.healthpluspharmacy.com/",
      dosage: "5 mg/0.5 mL",
      rating: "4.4",
      price: "128.59",
      quantity: "1",
      date: "15-01-2024",
    },
    {
      pharmacyName: "Wellness Pharmacy",
      websiteURL: "https://www.wellnesspharmacy.com/",
      dosage: "7.5 mg/0.5 mL",
      rating: "4.9",
      price: "129.74",
      quantity: "7",
      date: "19-11-2024",
    },
    {
      pharmacyName: "MediCare Pharmacy",
      websiteURL: "https://www.medicarepharmacy.com/",
      dosage: "10 mg/0.5 mL",
      rating: "4.9",
      price: "104.39",
      quantity: "16",
      date: "14-03-2024",
    },
    {
      pharmacyName: "LifeLine Pharmacy",
      websiteURL: "https://www.lifelinepharmacy.com/",
      dosage: "12.5 mg/0.5 mL",
      rating: "4.2",
      price: "114.92",
      quantity: "6",
      date: "03-08-2024",
    },
    {
      pharmacyName: "CityMed Pharmacy",
      websiteURL: "https://www.citymedpharmacy.com/",
      dosage: "15 mg/0.5 mL",
      rating: "4.4",
      price: "147.74",
      quantity: "11",
      date: "15-01-2024",
    },
    {
      pharmacyName: "PharmaCare",
      websiteURL: "https://www.pharmacare.com/",
      dosage: "2.5 mg/0.5 mL",
      rating: "4.9",
      price: "116.60",
      quantity: "16",
      date: "15-04-2024",
    },
    {
      pharmacyName: "HealthFirst Pharmacy",
      websiteURL: "https://www.healthfirstpharmacy.com/",
      dosage: "5 mg/0.5 mL",
      rating: "3.8",
      price: "136.99",
      quantity: "11",
      date: "04-05-2024",
    },
    {
      pharmacyName: "Trust Pharmacy",
      websiteURL: "https://www.trustpharmacy.com/",
      dosage: "7.5 mg/0.5 mL",
      rating: "4.9",
      price: "115.10",
      quantity: "20",
      date: "10-08-2024",
    },
    {
      pharmacyName: "GoodHealth Pharmacy",
      websiteURL: "https://www.goodhealthpharmacy.com/",
      dosage: "10 mg/0.5 mL",
      rating: "4.8",
      price: "100.05",
      quantity: "8",
      date: "29-03-2024",
    },
    {
        pharmacyName: "Care Pharmacy",
        websiteURL: "https://www.carepharmacy.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "3.8",
        price: "147.89",
        quantity: "20",
        date: "07-05-2024",
      },
      {
        pharmacyName: "HealthPlus Pharmacy",
        websiteURL: "https://www.healthpluspharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "4.4",
        price: "128.59",
        quantity: "1",
        date: "15-01-2024",
      },
      {
        pharmacyName: "Wellness Pharmacy",
        websiteURL: "https://www.wellnesspharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "129.74",
        quantity: "7",
        date: "19-11-2024",
      },
      {
        pharmacyName: "MediCare Pharmacy",
        websiteURL: "https://www.medicarepharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.9",
        price: "104.39",
        quantity: "16",
        date: "14-03-2024",
      },
      {
        pharmacyName: "LifeLine Pharmacy",
        websiteURL: "https://www.lifelinepharmacy.com/",
        dosage: "12.5 mg/0.5 mL",
        rating: "4.2",
        price: "114.92",
        quantity: "6",
        date: "03-08-2024",
      },
      {
        pharmacyName: "CityMed Pharmacy",
        websiteURL: "https://www.citymedpharmacy.com/",
        dosage: "15 mg/0.5 mL",
        rating: "4.4",
        price: "147.74",
        quantity: "11",
        date: "15-01-2024",
      },
      {
        pharmacyName: "PharmaCare",
        websiteURL: "https://www.pharmacare.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "4.9",
        price: "116.60",
        quantity: "16",
        date: "15-04-2024",
      },
      {
        pharmacyName: "HealthFirst Pharmacy",
        websiteURL: "https://www.healthfirstpharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "3.8",
        price: "136.99",
        quantity: "11",
        date: "04-05-2024",
      },
      {
        pharmacyName: "Trust Pharmacy",
        websiteURL: "https://www.trustpharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "115.10",
        quantity: "20",
        date: "10-08-2024",
      },
      {
        pharmacyName: "GoodHealth Pharmacy",
        websiteURL: "https://www.goodhealthpharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.8",
        price: "100.05",
        quantity: "8",
        date: "29-03-2024",
      },
      {
        pharmacyName: "Care Pharmacy",
        websiteURL: "https://www.carepharmacy.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "3.8",
        price: "147.89",
        quantity: "20",
        date: "07-05-2024",
      },
      {
        pharmacyName: "HealthPlus Pharmacy",
        websiteURL: "https://www.healthpluspharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "4.4",
        price: "128.59",
        quantity: "1",
        date: "15-01-2024",
      },
      {
        pharmacyName: "Wellness Pharmacy",
        websiteURL: "https://www.wellnesspharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "129.74",
        quantity: "7",
        date: "19-11-2024",
      },
      {
        pharmacyName: "MediCare Pharmacy",
        websiteURL: "https://www.medicarepharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.9",
        price: "104.39",
        quantity: "16",
        date: "14-03-2024",
      },
      {
        pharmacyName: "LifeLine Pharmacy",
        websiteURL: "https://www.lifelinepharmacy.com/",
        dosage: "12.5 mg/0.5 mL",
        rating: "4.2",
        price: "114.92",
        quantity: "6",
        date: "03-08-2024",
      },
      {
        pharmacyName: "CityMed Pharmacy",
        websiteURL: "https://www.citymedpharmacy.com/",
        dosage: "15 mg/0.5 mL",
        rating: "4.4",
        price: "147.74",
        quantity: "11",
        date: "15-01-2024",
      },
      {
        pharmacyName: "PharmaCare",
        websiteURL: "https://www.pharmacare.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "4.9",
        price: "116.60",
        quantity: "16",
        date: "15-04-2024",
      },
      {
        pharmacyName: "HealthFirst Pharmacy",
        websiteURL: "https://www.healthfirstpharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "3.8",
        price: "136.99",
        quantity: "11",
        date: "04-05-2024",
      },
      {
        pharmacyName: "Trust Pharmacy",
        websiteURL: "https://www.trustpharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "115.10",
        quantity: "20",
        date: "10-08-2024",
      },
      {
        pharmacyName: "GoodHealth Pharmacy",
        websiteURL: "https://www.goodhealthpharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.8",
        price: "100.05",
        quantity: "8",
        date: "29-03-2024",
      },
      {
        pharmacyName: "Care Pharmacy",
        websiteURL: "https://www.carepharmacy.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "3.8",
        price: "147.89",
        quantity: "20",
        date: "07-05-2024",
      },
      {
        pharmacyName: "HealthPlus Pharmacy",
        websiteURL: "https://www.healthpluspharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "4.4",
        price: "128.59",
        quantity: "1",
        date: "15-01-2024",
      },
      {
        pharmacyName: "Wellness Pharmacy",
        websiteURL: "https://www.wellnesspharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "129.74",
        quantity: "7",
        date: "19-11-2024",
      },
      {
        pharmacyName: "MediCare Pharmacy",
        websiteURL: "https://www.medicarepharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.9",
        price: "104.39",
        quantity: "16",
        date: "14-03-2024",
      },
      {
        pharmacyName: "LifeLine Pharmacy",
        websiteURL: "https://www.lifelinepharmacy.com/",
        dosage: "12.5 mg/0.5 mL",
        rating: "4.2",
        price: "114.92",
        quantity: "6",
        date: "03-08-2024",
      },
      {
        pharmacyName: "CityMed Pharmacy",
        websiteURL: "https://www.citymedpharmacy.com/",
        dosage: "15 mg/0.5 mL",
        rating: "4.4",
        price: "147.74",
        quantity: "11",
        date: "15-01-2024",
      },
      {
        pharmacyName: "PharmaCare",
        websiteURL: "https://www.pharmacare.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "4.9",
        price: "116.60",
        quantity: "16",
        date: "15-04-2024",
      },
      {
        pharmacyName: "HealthFirst Pharmacy",
        websiteURL: "https://www.healthfirstpharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "3.8",
        price: "136.99",
        quantity: "11",
        date: "04-05-2024",
      },
      {
        pharmacyName: "Trust Pharmacy",
        websiteURL: "https://www.trustpharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "115.10",
        quantity: "20",
        date: "10-08-2024",
      },
      {
        pharmacyName: "GoodHealth Pharmacy",
        websiteURL: "https://www.goodhealthpharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.8",
        price: "100.05",
        quantity: "8",
        date: "29-03-2024",
      },
      {
        pharmacyName: "Care Pharmacy",
        websiteURL: "https://www.carepharmacy.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "3.8",
        price: "147.89",
        quantity: "20",
        date: "07-05-2024",
      },
      {
        pharmacyName: "HealthPlus Pharmacy",
        websiteURL: "https://www.healthpluspharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "4.4",
        price: "128.59",
        quantity: "1",
        date: "15-01-2024",
      },
      {
        pharmacyName: "Wellness Pharmacy",
        websiteURL: "https://www.wellnesspharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "129.74",
        quantity: "7",
        date: "19-11-2024",
      },
      {
        pharmacyName: "MediCare Pharmacy",
        websiteURL: "https://www.medicarepharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.9",
        price: "104.39",
        quantity: "16",
        date: "14-03-2024",
      },
      {
        pharmacyName: "LifeLine Pharmacy",
        websiteURL: "https://www.lifelinepharmacy.com/",
        dosage: "12.5 mg/0.5 mL",
        rating: "4.2",
        price: "114.92",
        quantity: "6",
        date: "03-08-2024",
      },
      {
        pharmacyName: "CityMed Pharmacy",
        websiteURL: "https://www.citymedpharmacy.com/",
        dosage: "15 mg/0.5 mL",
        rating: "4.4",
        price: "147.74",
        quantity: "11",
        date: "15-01-2024",
      },
      {
        pharmacyName: "PharmaCare",
        websiteURL: "https://www.pharmacare.com/",
        dosage: "2.5 mg/0.5 mL",
        rating: "4.9",
        price: "116.60",
        quantity: "16",
        date: "15-04-2024",
      },
      {
        pharmacyName: "HealthFirst Pharmacy",
        websiteURL: "https://www.healthfirstpharmacy.com/",
        dosage: "5 mg/0.5 mL",
        rating: "3.8",
        price: "136.99",
        quantity: "11",
        date: "04-05-2024",
      },
      {
        pharmacyName: "Trust Pharmacy",
        websiteURL: "https://www.trustpharmacy.com/",
        dosage: "7.5 mg/0.5 mL",
        rating: "4.9",
        price: "115.10",
        quantity: "20",
        date: "10-08-2024",
      },
      {
        pharmacyName: "GoodHealth Pharmacy",
        websiteURL: "https://www.goodhealthpharmacy.com/",
        dosage: "10 mg/0.5 mL",
        rating: "4.8",
        price: "100.05",
        quantity: "8",
        date: "29-03-2024",
      },
    // …and 40 more entries in the same pattern
  ];
  

export default mounjaroData;
