const wegovyData = [
  {id: 1,
    pharmacyName: "Care Pharmacy",
    websiteURL: "https://www.carepharmacy.com/",
    dosage: "0.25 mg/0.5 mL",
    rating: "5.0",
    price: "129.52",
    quantity: "1",
    date: "10-07-2024",
  },
  {
    id: 2,
    pharmacyName: "HealthPlus Pharmacy",
    websiteURL: "https://www.healthpluspharmacy.com/",
    dosage: "0.5 mg/0.5 mL",
    rating: "4.6",
    price: "177.03",
    quantity: "16",
    date: "28-06-2024",
  },
  {
    id: 3,
    pharmacyName: "Wellness Pharmacy",
    websiteURL: "https://www.wellnesspharmacy.com/",
    dosage: "1.0 mg/0.5 mL",
    rating: "3.7",
    price: "162.39",
    quantity: "5",
    date: "18-02-2024",
  },
  {
    id: 4,
    pharmacyName: "MediCare Pharmacy",
    websiteURL: "https://www.medicarepharmacy.com/",
    dosage: "1.7 mg/0.75 mL",
    rating: "4.9",
    price: "143.52",
    quantity: "18",
    date: "01-03-2024",
  },
  {
    id: 5,
    pharmacyName: "LifeLine Pharmacy",
    websiteURL: "https://www.lifelinepharmacy.com/",
    dosage: "2.4 mg/0.75 mL",
    rating: "4.9",
    price: "176.08",
    quantity: "17",
    date: "16-02-2024",
  },
  {
    id: 6,
    pharmacyName: "CityMed Pharmacy",
    websiteURL: "https://www.citymedpharmacy.com/",
    dosage: "0.25 mg/0.5 mL",
    rating: "4.2",
    price: "143.33",
    quantity: "5",
    date: "08-01-2024",
  },
  {
    id: 7,
    pharmacyName: "PharmaCare",
    websiteURL: "https://www.pharmacare.com/",
    dosage: "0.5 mg/0.5 mL",
    rating: "4.0",
    price: "163.50",
    quantity: "5",
    date: "23-03-2024",
  },
  {
    id: 8,
    pharmacyName: "HealthFirst Pharmacy",
    websiteURL: "https://www.healthfirstpharmacy.com/",
    dosage: "1.0 mg/0.5 mL",
    rating: "4.6",
    price: "153.42",
    quantity: "4",
    date: "27-06-2024",
  },
  {
    id: 9,
    pharmacyName: "Trust Pharmacy",
    websiteURL: "https://www.trustpharmacy.com/",
    dosage: "1.7 mg/0.75 mL",
    rating: "4.2",
    price: "142.05",
    quantity: "10",
    date: "05-01-2024",
  },
  {
    id: 10,
    pharmacyName: "GoodHealth Pharmacy",
    websiteURL: "https://www.goodhealthpharmacy.com/",
    dosage: "2.4 mg/0.75 mL",
    rating: "4.1",
    price: "143.26",
    quantity: "11",
    date: "08-06-2024",
  },
  {
    id: 11,
    pharmacyName: "PharmaCare",
    websiteURL: "https://www.pharmacare.com/",
    dosage: "0.5 mg/0.5 mL",
    rating: "4.0",
    price: "163.50",
    quantity: "5",
    date: "23-03-2024",
  },
  {
    id: 12,
    pharmacyName: "HealthFirst Pharmacy",
    websiteURL: "https://www.healthfirstpharmacy.com/",
    dosage: "1.0 mg/0.5 mL",
    rating: "4.6",
    price: "153.42",
    quantity: "4",
    date: "27-06-2024",
  },
  {
    id: 13,
    pharmacyName: "Trust Pharmacy",
    websiteURL: "https://www.trustpharmacy.com/",
    dosage: "1.7 mg/0.75 mL",
    rating: "4.2",
    price: "142.05",
    quantity: "10",
    date: "05-01-2024",
  },
  {
    id: 14,
    pharmacyName: "GoodHealth Pharmacy",
    websiteURL: "https://www.goodhealthpharmacy.com/",
    dosage: "2.4 mg/0.75 mL",
    rating: "4.1",
    price: "143.26",
    quantity: "11",
    date: "08-06-2024",
  },
  {
    id: 15,
    pharmacyName: "PharmaCare",
    websiteURL: "https://www.pharmacare.com/",
    dosage: "0.5 mg/0.5 mL",
    rating: "4.0",
    price: "163.50",
    quantity: "5",
    date: "23-03-2024",
  },
  {
    id: 16,
    pharmacyName: "HealthFirst Pharmacy",
    websiteURL: "https://www.healthfirstpharmacy.com/",
    dosage: "1.0 mg/0.5 mL",
    rating: "4.6",
    price: "153.42",
    quantity: "4",
    date: "27-06-2024",
  },
  {
    id: 17,
    pharmacyName: "Trust Pharmacy",
    websiteURL: "https://www.trustpharmacy.com/",
    dosage: "1.7 mg/0.75 mL",
    rating: "4.2",
    price: "142.05",
    quantity: "10",
    date: "05-01-2024",
  },
  {
    id: 18,
    pharmacyName: "GoodHealth Pharmacy",
    websiteURL: "https://www.goodhealthpharmacy.com/",
    dosage: "2.4 mg/0.75 mL",
    rating: "4.1",
    price: "143.26",
    quantity: "11",
    date: "08-06-2024",
  },
  {
    id: 19,
    pharmacyName: "PharmaCare",
    websiteURL: "https://www.pharmacare.com/",
    dosage: "0.5 mg/0.5 mL",
    rating: "4.0",
    price: "163.50",
    quantity: "5",
    date: "23-03-2024",
  },
  {
    id: 20,
    pharmacyName: "HealthFirst Pharmacy",
    websiteURL: "https://www.healthfirstpharmacy.com/",
    dosage: "1.0 mg/0.5 mL",
    rating: "4.6",
    price: "153.42",
    quantity: "4",
    date: "27-06-2024",
  },
  {
    id: 21,
    pharmacyName: "Trust Pharmacy",
    websiteURL: "https://www.trustpharmacy.com/",
    dosage: "1.7 mg/0.75 mL",
    rating: "4.2",
    price: "142.05",
    quantity: "10",
    date: "05-01-2024",
  },
  {
    id: 22,
    pharmacyName: "GoodHealth Pharmacy",
    websiteURL: "https://www.goodhealthpharmacy.com/",
    dosage: "2.4 mg/0.75 mL",
    rating: "4.1",
    price: "143.26",
    quantity: "11",
    date: "08-06-2024",
  },
  // …plus 40 more entries following the same pattern
];

export default wegovyData;
